"""phase3 alerts options decisions

Revision ID: 32cab3e3389b
Revises: 6928a97e0861
Create Date: 2026-08-26 10:52:01.036295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32cab3e3389b'
down_revision: Union[str, Sequence[str], None] = '6928a97e0861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('rule_code', sa.String(length=40), nullable=False),
    sa.Column('rule_version', sa.String(length=10), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('provenance', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_id', 'rule_code', name='uq_alert_shipment_rule')
    )
    op.create_index(op.f('ix_alerts_shipment_id'), 'alerts', ['shipment_id'], unique=False)
    op.create_table('decision_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('option_type', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('days_saved', sa.Float(), nullable=True),
    sa.Column('p_on_time', sa.Float(), nullable=True),
    sa.Column('co2_delta_kg', sa.Float(), nullable=True),
    sa.Column('expected_total_cost_usd', sa.Float(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_options_alert_id'), 'decision_options', ['alert_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('decided_by', sa.String(length=120), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=400), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_alert_id'), 'decisions', ['alert_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decisions_alert_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_decision_options_alert_id'), table_name='decision_options')
    op.drop_table('decision_options')
    op.drop_index(op.f('ix_alerts_shipment_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
