"""phase2 geo and telemetry tables

Revision ID: 6928a97e0861
Revises: f52400b2b578
Create Date: 2026-08-26 06:22:56.453881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6928a97e0861'
down_revision: Union[str, Sequence[str], None] = 'f52400b2b578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aircraft',
    sa.Column('icao24', sa.String(length=10), nullable=False),
    sa.Column('callsign', sa.String(length=12), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('alt_m', sa.Float(), nullable=True),
    sa.Column('speed_ms', sa.Float(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('feed', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('icao24')
    )
    op.create_table('airports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iata', sa.String(length=5), nullable=False),
    sa.Column('icao', sa.String(length=8), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iata')
    )
    op.create_table('lanes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lane_key', sa.String(length=80), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('origin_name', sa.String(length=120), nullable=False),
    sa.Column('dest_name', sa.String(length=120), nullable=False),
    sa.Column('origin_lat', sa.Float(), nullable=False),
    sa.Column('origin_lon', sa.Float(), nullable=False),
    sa.Column('dest_lat', sa.Float(), nullable=False),
    sa.Column('dest_lon', sa.Float(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('geojson', sa.JSON(), nullable=True),
    sa.Column('provenance', sa.String(length=40), nullable=False),
    sa.Column('source_citation', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lane_key')
    )
    op.create_table('ports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wpi_number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('locode', sa.String(length=10), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('harbor_size', sa.String(length=30), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('position_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=10), nullable=False),
    sa.Column('entity_id', sa.String(length=20), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('provenance', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_reports_entity_id'), 'position_reports', ['entity_id'], unique=False)
    op.create_index(op.f('ix_position_reports_ts'), 'position_reports', ['ts'], unique=False)
    op.create_table('vessels',
    sa.Column('mmsi', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('vessel_class', sa.String(length=60), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('speed_kn', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('destination', sa.String(length=120), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('feed', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('mmsi')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vessels')
    op.drop_index(op.f('ix_position_reports_ts'), table_name='position_reports')
    op.drop_index(op.f('ix_position_reports_entity_id'), table_name='position_reports')
    op.drop_table('position_reports')
    op.drop_table('ports')
    op.drop_table('lanes')
    op.drop_table('airports')
    op.drop_table('aircraft')
    # ### end Alembic commands ###
