"""phase1 initial schema

Revision ID: f52400b2b578
Revises: 
Create Date: 2026-08-26 05:46:37.343776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f52400b2b578'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibrated_params',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('source_citation', sa.String(length=300), nullable=False),
    sa.Column('source_file', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('calibrated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataco_customer_id', sa.Integer(), nullable=False),
    sa.Column('segment', sa.String(length=40), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('market', sa.String(length=60), nullable=True),
    sa.Column('provenance', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_dataco_customer_id'), 'customers', ['dataco_customer_id'], unique=True)
    op.create_table('dataco_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('ship_date', sa.DateTime(), nullable=True),
    sa.Column('ship_mode', sa.String(length=40), nullable=True),
    sa.Column('delivery_status', sa.String(length=40), nullable=True),
    sa.Column('late_risk', sa.Integer(), nullable=False),
    sa.Column('days_scheduled', sa.Integer(), nullable=False),
    sa.Column('days_real', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('sales', sa.Float(), nullable=False),
    sa.Column('item_price', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('profit', sa.Float(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_segment', sa.String(length=40), nullable=True),
    sa.Column('order_city', sa.String(length=120), nullable=True),
    sa.Column('order_country', sa.String(length=120), nullable=True),
    sa.Column('order_region', sa.String(length=120), nullable=True),
    sa.Column('market', sa.String(length=60), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('order_status', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'order_item_id', name='uq_dataco_line')
    )
    op.create_index('ix_dataco_mode', 'dataco_orders', ['ship_mode'], unique=False)
    op.create_index(op.f('ix_dataco_orders_customer_id'), 'dataco_orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_dataco_orders_order_id'), 'dataco_orders', ['order_id'], unique=False)
    op.create_index(op.f('ix_dataco_orders_product_name'), 'dataco_orders', ['product_name'], unique=False)
    op.create_table('disruption_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=120), nullable=False),
    sa.Column('port_name', sa.String(length=160), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('days_reduction', sa.Integer(), nullable=True),
    sa.Column('days_shutdown', sa.Integer(), nullable=True),
    sa.Column('days_recovery', sa.Integer(), nullable=True),
    sa.Column('total_affected_days', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event', 'port_name', name='uq_disruption')
    )
    op.create_table('event_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('provenance', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_log_entity_id'), 'event_log', ['entity_id'], unique=False)
    op.create_table('legs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('origin', sa.String(length=120), nullable=False),
    sa.Column('destination', sa.String(length=120), nullable=True),
    sa.Column('planned_dep', sa.DateTime(), nullable=True),
    sa.Column('planned_arr', sa.DateTime(), nullable=True),
    sa.Column('actual_dep', sa.DateTime(), nullable=True),
    sa.Column('actual_arr', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provenance', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legs_shipment_id'), 'legs', ['shipment_id'], unique=False)
    op.create_table('port_dwell_priors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('economy', sa.String(length=120), nullable=False),
    sa.Column('vessel_type', sa.String(length=120), nullable=False),
    sa.Column('median_time_in_port_days', sa.Float(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('economy', 'vessel_type', 'period', name='uq_dwell')
    )
    op.create_index(op.f('ix_port_dwell_priors_economy'), 'port_dwell_priors', ['economy'], unique=False)
    op.create_table('shipment_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('line_value', sa.Float(), nullable=False),
    sa.Column('provenance', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_lines_shipment_id'), 'shipment_lines', ['shipment_id'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref', sa.String(length=40), nullable=False),
    sa.Column('dataco_order_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('dest_city', sa.String(length=120), nullable=True),
    sa.Column('dest_country', sa.String(length=120), nullable=True),
    sa.Column('dest_region', sa.String(length=120), nullable=True),
    sa.Column('market', sa.String(length=60), nullable=True),
    sa.Column('dest_lat', sa.Float(), nullable=True),
    sa.Column('dest_lon', sa.Float(), nullable=True),
    sa.Column('freight_mode', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('value_usd', sa.Float(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('planned_ship_date', sa.DateTime(), nullable=True),
    sa.Column('sla_due_at', sa.DateTime(), nullable=True),
    sa.Column('actual_delivery', sa.DateTime(), nullable=True),
    sa.Column('was_late', sa.Boolean(), nullable=False),
    sa.Column('provenance', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref')
    )
    op.create_index(op.f('ix_shipments_dataco_order_id'), 'shipments', ['dataco_order_id'], unique=False)
    op.create_table('skus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('unit_price_usd', sa.Float(), nullable=False),
    sa.Column('provenance', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sop_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('condition', sa.JSON(), nullable=True),
    sa.Column('action_template', sa.String(length=500), nullable=True),
    sa.Column('authority_role', sa.String(length=40), nullable=True),
    sa.Column('reference_doc', sa.String(length=200), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'version', name='uq_sop_code_version')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('approval_limit_usd', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('sop_rules')
    op.drop_table('skus')
    op.drop_index(op.f('ix_shipments_dataco_order_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_shipment_lines_shipment_id'), table_name='shipment_lines')
    op.drop_table('shipment_lines')
    op.drop_index(op.f('ix_port_dwell_priors_economy'), table_name='port_dwell_priors')
    op.drop_table('port_dwell_priors')
    op.drop_index(op.f('ix_legs_shipment_id'), table_name='legs')
    op.drop_table('legs')
    op.drop_index(op.f('ix_event_log_entity_id'), table_name='event_log')
    op.drop_table('event_log')
    op.drop_table('disruption_records')
    op.drop_index(op.f('ix_dataco_orders_product_name'), table_name='dataco_orders')
    op.drop_index(op.f('ix_dataco_orders_order_id'), table_name='dataco_orders')
    op.drop_index(op.f('ix_dataco_orders_customer_id'), table_name='dataco_orders')
    op.drop_index('ix_dataco_mode', table_name='dataco_orders')
    op.drop_table('dataco_orders')
    op.drop_index(op.f('ix_customers_dataco_customer_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('calibrated_params')
    # ### end Alembic commands ###
