/**
 * NexaFreight client library — public exports
 *
 * Import from here rather than the individual modules:
 *   import { nexaClient, NexaHttpError, type ShipmentListItem } from '@/lib/nexafreight'
 */

// Types
export type {
  UserRole,
  TransportMode,
  ShipmentStatus,
  LegStatus,
  Provenance,
  OrderSlaStatus,
  LoginRequest,
  LoginResponse,
  UserProfile,
  User,
  PaginatedResponse,
  ShipmentListItem,
  ShipmentDetail,
  Leg,
  LegDetail,
  VesselInfo,
  Order,
  OrderSummary,
  Event,
  ShipmentEvent,
  Port,
  PortFeature,
  PortFeatureCollection,
  PortFeatureProperties,
  RouteQuality,
  GeoJSONGeometry,
  RouteFeature,
  RouteFeatureCollection,
  PositionReport,
  PositionOut,
  FeedHealth,
  FeedHealthOut,
  FeedHealthResponse,
  RiskBand,
  MLResponseBase,
  MLPredictionRequest,
  DelayPrediction,
  EtaPrediction,
  DemandForecastSeriesPoint,
  DemandForecastResponse,
  ForecastUnavailable,
  MLErrorResponse,
} from './types'

// Errors
export { NexaError, NexaHttpError, NexaNetworkError } from './errors'

// Client functions + convenience namespace
export {
  setToken,
  clearToken,
  getToken,
  hasToken,
  BASE_URL,
  login,
  getCurrentUser,
  getShipments,
  getShipmentDetail,
  getShipmentRoute,
  getPorts,
  getWarehouses,
  getAllRoutes,
  getFeedHealth,
  getDelayPrediction,
  getEtaPrediction,
  getDemandForecast,
  nexaClient,
  type GetShipmentsParams,
} from './client'


// Phase 10-12 operational types (Definitive Plan)
export type {
  AlertSeverity,
  AlertStatus,
  DisruptionType,
  DisruptionStatus,
  DecisionAction,
  Alert,
  AlertDetail,
  AlertsResponse,
  AcknowledgeRequest,
  SlaBreach,
  RerouteOption,
  RerouteOptionsResponse,
  ApproveResponse,
  Decision,
  DecisionsResponse,
  Disruption,
  DisruptionsResponse,
  DisruptionCreate,
  ShipmentSummary,
  AnalyticsSummaryResponse,
  WindowSlice,
  AnalyticsFinancialRow,
  AnalyticsFinancialResponse,
  SlaRow,
  AnalyticsSlaResponse,
  EsgRow,
  AnalyticsEsgResponse,
  ShipmentPredictResponse,
  FinancialOrder,
  PnlSnapshot,
  ShipmentFinancialsResponse,
  CopilotAskResponse,
} from './types'

export {
  getAlerts,
  getAlert,
  acknowledgeAlert,
  getAlertOptions,
  approveAlertOption,
  getDisruptions,
  getDisruption,
  reportDisruption,
  getDecisions,
  getDecision,
  getAnalyticsSummary,
  getAnalyticsScorecard,
  getAnalyticsSla,
  getAnalyticsEsg,
  askCopilot,
  getShipmentPrediction,
  getShipmentFinancials,
} from './client'
