/**
 * NexaFreight API — TypeScript types
 *
 * Generated by hand from the backend Pydantic schemas:
 *   src/nexafreight/schemas/auth.py
 *   src/nexafreight/schemas/shipment.py
 *   src/nexafreight/schemas/common.py
 *   src/nexafreight/enums.py
 *
 * DO NOT guess field names. If the backend changes, update here first.
 * Contract drift between these types and the Pydantic models is the #1
 * integration failure mode (per project doc).
 */

// ─── Enums ────────────────────────────────────────────────────────────────────
// Values are StrEnum on the backend — serialised as-is (uppercase strings).

/** src/nexafreight/enums.py :: UserRole */
export type UserRole = 'ADMIN' | 'OPERATOR' | 'VIEWER'

/** src/nexafreight/enums.py :: TransportMode */
export type TransportMode = 'SEA' | 'AIR' | 'ROAD' | 'RAIL'

/** src/nexafreight/enums.py :: ShipmentStatus */
export type ShipmentStatus =
  | 'PLANNED'
  | 'IN_TRANSIT'
  | 'DELIVERED'
  | 'DELAYED'
  | 'CANCELLED'

/** src/nexafreight/enums.py :: LegStatus */
export type LegStatus =
  | 'PLANNED'
  | 'IN_PROGRESS'
  | 'COMPLETED'
  | 'REPLACED'
  | 'CANCELLED'

/** src/nexafreight/enums.py :: Provenance */
export type Provenance =
  | 'REAL'
  | 'REPLAYED'
  | 'DERIVED'
  | 'CALIBRATED'
  | 'SIMULATED'
  | 'MOCK'

/** src/nexafreight/enums.py :: OrderSlaStatus */
export type OrderSlaStatus = 'ON_TIME' | 'AT_RISK' | 'LATE'

// ─── Auth ─────────────────────────────────────────────────────────────────────

/**
 * POST /api/auth/login — request body
 * src/nexafreight/schemas/auth.py :: LoginRequest
 */
export interface LoginRequest {
  email: string
  password: string
}

/**
 * Nested user profile returned inside LoginResponse.
 * src/nexafreight/schemas/auth.py :: UserProfile
 *
 * Note: role is a plain string in this schema (not the UserRole enum),
 * but in practice the backend always sends one of the UserRole values.
 */
export interface UserProfile {
  email: string
  full_name: string
  role: string
  is_active: boolean
}

/**
 * POST /api/auth/login — successful response body
 * src/nexafreight/schemas/auth.py :: LoginResponse
 */
export interface LoginResponse {
  access_token: string
  token_type: string   // always "bearer"
  user: UserProfile
  expires_in: number   // seconds (not minutes)
}

/**
 * GET /api/auth/me — response body
 * src/nexafreight/schemas/auth.py :: UserOut
 *
 * Different shape from UserProfile: adds `id`, drops `is_active`.
 * full_name is nullable here.
 */
export interface User {
  id: number
  email: string
  role: UserRole
  full_name: string | null
}

// ─── Pagination envelope ──────────────────────────────────────────────────────

/**
 * Generic pagination wrapper used by list endpoints.
 * src/nexafreight/schemas/common.py :: PaginatedResponse[T]
 */
export interface PaginatedResponse<T> {
  items: T[]
  total: number        // total matching records across all pages
  page: number         // current page, 1-indexed
  size: number         // items per page
  total_pages: number
}

// ─── Shipments ────────────────────────────────────────────────────────────────

/**
 * One row in GET /api/shipments list.
 * src/nexafreight/schemas/shipment.py :: ShipmentListItem
 *
 * Field names are exact — see Step 2 notes for fields the task doc mentioned
 * that do NOT exist on the backend (reference, dest, provenance).
 */
export interface ShipmentListItem {
  id: string                           // UUID string
  origin: string                       // UN/LOCODE
  destination: string                  // UN/LOCODE — backend field is "destination", not "dest"
  mode: TransportMode
  status: ShipmentStatus
  strictest_sla_deadline: string | null  // ISO-8601 datetime string
  revised_eta: string | null             // ISO-8601 datetime string; ML placeholder for now
}

/**
 * Vessel info nested inside Leg / LegDetail.
 * src/nexafreight/schemas/shipment.py :: VesselInfo
 */
export interface VesselInfo {
  name: string
  mmsi: number
}

/**
 * Route quality classification derived from provenance.
 * src/nexafreight/schemas/shipment.py :: RouteQuality
 *
 * - "high": REAL or CALIBRATED provenance (actual data)
 * - "medium": REPLAYED or DERIVED (historical/computed)
 * - "low": SIMULATED or MOCK (synthetic)
 * - "unknown": other / unrecognized
 */
export type RouteQuality = 'high' | 'medium' | 'low' | 'unknown' | 'PRECISE' | 'APPROXIMATE' | string

/**
 * Generic GeoJSON geometry object.
 */
export type GeoJSONGeometry = GeoJSON.Geometry

/**
 * One route segment (leg) in a shipment or route plan.
 * Matches backend schemas (LegDetail, RouteFeature) and map routing representations.
 *
 * Fields requested in Phase 2 Step 1:
 *   id, leg_type, sequence, mode, geometry as GeoJSON, route_quality, planned_departure, planned_arrival
 */
export interface Leg {
  id: number | string
  leg_type?: string
  sequence?: number
  sequence_number?: number             // 1-indexed (backend field)
  mode: TransportMode
  status?: LegStatus
  route_version?: number
  origin?: string                      // UN/LOCODE
  destination?: string                 // UN/LOCODE
  geometry?: GeoJSON.Geometry | null
  route_geometry?: GeoJSON.Geometry | null
  route_quality?: RouteQuality
  planned_departure: string            // ISO-8601
  planned_arrival: string              // ISO-8601
  actual_departure?: string | null     // ISO-8601, null if not yet departed
  actual_arrival?: string | null       // ISO-8601, null if not yet arrived
  distance_km?: number | null
  co2_kg?: number | null
  provenance?: Provenance | string
  vessel?: VesselInfo | null
  flight_number?: string | null
}

/**
 * Detailed information about one leg in a shipment's route.
 * src/nexafreight/schemas/shipment.py :: LegDetail
 */
export interface LegDetail extends Leg {
  id: number
  sequence_number: number              // 1-indexed
  status: LegStatus
  route_version: number
  origin: string
  destination: string
  provenance: Provenance
}

/**
 * One order summary nested inside ShipmentDetail.
 * src/nexafreight/schemas/shipment.py :: OrderSummary
 */
export interface OrderSummary {
  id: number | string
  order_number?: string
  sla_deadline: string                 // ISO-8601
  revenue?: number                     // USD
  sla_status?: OrderSlaStatus
}

/** Alias for OrderSummary */
export type Order = OrderSummary

/**
 * One entry from GET /api/shipments/{id}/events.
 * src/nexafreight/schemas/shipment.py :: ShipmentEvent
 */
export interface ShipmentEvent {
  id?: string | number
  timestamp: string                    // ISO-8601
  type?: string
  event_type?: string
  message?: string
  description?: string
  actor?: string | null
}

/** Alias for ShipmentEvent */
export type Event = ShipmentEvent

/**
 * Full detail for GET /api/shipments/{id}.
 * src/nexafreight/schemas/shipment.py :: ShipmentDetail
 *
 * Extends ShipmentListItem with route segments (legs), associated orders, and events.
 */
export interface ShipmentDetail extends ShipmentListItem {
  reference?: string
  dest?: string
  destination: string
  cargo_class?: string
  route_version?: number
  container_count?: number
  provenance?: string
  legs: Leg[]
  orders: Order[]
  events?: Event[]
}

// ─── GeoJSON & Map ────────────────────────────────────────────────────────────

/**
 * Feature properties for a route segment feature.
 * src/nexafreight/schemas/shipment.py :: RouteFeature
 * src/nexafreight/routers/map.py :: _execute_routes_query
 */
export interface RouteFeatureProperties {
  leg_id?: string
  shipment_id?: string
  mode?: TransportMode | string
  status?: LegStatus | string
  provenance?: Provenance | string
  sequence?: number
  route_quality?: RouteQuality
  [key: string]: unknown
}

/**
 * One GeoJSON Feature in the route FeatureCollection.
 * src/nexafreight/schemas/shipment.py :: RouteFeature
 */
export type RouteFeature = GeoJSON.Feature<GeoJSON.Geometry, RouteFeatureProperties>

/**
 * GeoJSON FeatureCollection for shipment route visualization.
 * src/nexafreight/schemas/shipment.py :: RouteFeatureCollection
 *
 * Returned by GET /api/shipments/{id}/route and GET /api/map/routes.
 * Typed loosely as GeoJSON.FeatureCollection since geometry shapes vary by mode.
 */
export type RouteFeatureCollection = GeoJSON.FeatureCollection

// ─── Ports ────────────────────────────────────────────────────────────────────

/**
 * Port master data and congestion stats.
 * Matches backend models (Port, Location, PortDailyStat) and T-015 port_daily_stats fields.
 * Endpoint: /api/map/ports or database model Port + Location + PortDailyStat
 */
export interface Port {
  id: number | string
  un_locode: string
  locode?: string
  name: string
  lat: number
  lon: number
  latitude?: number
  longitude?: number
  country_code?: string
  congestion_index: number | null
  vessel_count?: number | null
  rolling_90d_avg?: number | null
  provenance?: string
}

/**
 * Properties object for a Port feature inside a GeoJSON FeatureCollection.
 * Returned by GET /api/map/ports.
 */
export interface PortFeatureProperties {
  port_id: string
  location_id?: string | null
  un_locode?: string
  locode?: string
  name: string
  congestion_index: number | null
  provenance?: string
  [key: string]: unknown
}

/**
 * GeoJSON Point feature for port markers on map.
 */
export type PortFeature = GeoJSON.Feature<GeoJSON.Point, PortFeatureProperties>

/**
 * GeoJSON FeatureCollection for port markers and congestion overlay.
 * Returned by GET /api/map/ports.
 */
export type PortFeatureCollection = GeoJSON.FeatureCollection<GeoJSON.Point, PortFeatureProperties>

/**
 * Properties for a warehouse GeoJSON Point feature.
 */
export interface WarehouseFeatureProperties {
  warehouse_id: string
  name: string
}

/**
 * GeoJSON FeatureCollection for warehouse markers.
 */
export type WarehouseFeatureCollection = GeoJSON.FeatureCollection<GeoJSON.Point, WarehouseFeatureProperties>

// ─── Live Positions & Telemetry ───────────────────────────────────────────────

/**
 * Live position report matching T-026 / T-031 / Phase 3 specifications.
 * PositionReport: { asset_type: "VESSEL"|"TRUCK"|"FLIGHT", asset_id, lat, lon, speed_knots, heading_deg, provenance: "REAL"|"REPLAYED"|"SIMULATED", source, timestamp }
 */
export interface PositionReport {
  asset_type: 'VESSEL' | 'TRUCK' | 'FLIGHT' | 'SEA' | 'ROAD' | 'AIR' | string
  asset_id: string
  lat: number
  lon: number
  latitude?: number
  longitude?: number
  speed_knots: number | null
  heading_deg: number | null
  provenance: 'REAL' | 'REPLAYED' | 'SIMULATED' | Provenance | string
  source: string
  timestamp: string
  recorded_at?: string
  reported_at?: string | null
}

/**
 * Backward-compatible alias / canonical map position DTO.
 * src/nexafreight/schemas/map.py :: PositionOut
 */
export interface PositionOut {
  asset_id: string
  asset_type: TransportMode | string   // SEA | ROAD | AIR | RAIL
  latitude: number
  longitude: number
  lat?: number | null
  lon?: number | null
  speed_knots?: number | null
  heading_deg?: number | null
  provenance: Provenance | string
  recorded_at: string                  // ISO-8601
  reported_at?: string | null          // ISO-8601
  source: string
}

/**
 * Per-adapter status object from GET /api/map/feed-health.
 * src/nexafreight/schemas/map.py :: FeedHealthOut
 */
export interface FeedHealth {
  adapter_name: string
  is_healthy: boolean
  last_success_at: string | null       // ISO-8601
  messages_received: number
  provenance: 'REAL' | 'REPLAYED' | 'SIMULATED' | Provenance | string
}

/**
 * Alias for FeedHealth matching backend schema naming.
 */
export type FeedHealthOut = FeedHealth

/**
 * Response for GET /api/map/feed-health.
 * src/nexafreight/schemas/map.py :: FeedHealthResponse
 */
export interface FeedHealthResponse {
  adapters: FeedHealth[]
}

// ─── ML Predictions ───────────────────────────────────────────────────────────
// Matches backend: src/nexafreight/api/schemas/ml.py
// Routes:
//   POST /api/predict/delay   → DelayPrediction
//   POST /api/predict/eta     → EtaPrediction
//   GET  /api/demand/forecast → DemandForecastResponse | ForecastUnavailable

/** Risk band classification from delay probability. */
export type RiskBand = 'LOW' | 'MEDIUM' | 'HIGH'

/**
 * Shared fields on every ML prediction response.
 * src/nexafreight/api/schemas/ml.py :: _MLResponseBase
 */
export interface MLResponseBase {
  model_version: string
  schema_version: string
  provenance: 'DERIVED' | string
  /** Reserved for T-049D OSINT disruption-flag payloads. Always null currently. */
  context: Record<string, unknown> | null
}

/**
 * Request body for POST /api/predict/delay and POST /api/predict/eta.
 * src/nexafreight/api/schemas/ml.py :: DelayPredictionRequest / EtaPredictionRequest
 * Both endpoints accept the same 14 features.
 */
export interface MLPredictionRequest {
  shipping_mode: 'AIR' | 'SEA' | 'RAIL' | 'ROAD' | string
  cargo_class: 'STANDARD' | 'HIGH_VALUE' | 'REFRIGERATED' | string
  revenue: number
  shipping_cost: number
  scheduled_shipping_days: number
  order_country: string
  customer_country: string
  product_price: number
  order_profit: number
  sla_month: number         // 1–12
  sla_weekday: number       // 0–6 (Mon=0)
  sla_quarter: number       // 1–4
  total_distance_km: number
  leg_count: number         // ≥ 1
}

/**
 * POST /api/predict/delay — response body.
 * src/nexafreight/api/schemas/ml.py :: DelayPredictionResponse
 *
 * probability in [0, 1]. risk_band: LOW (<0.3) | MEDIUM (<0.6) | HIGH (≥0.6).
 */
export interface DelayPrediction extends MLResponseBase {
  probability: number   // [0.0, 1.0] — delay probability
  risk_band: RiskBand   // LOW | MEDIUM | HIGH
}

/**
 * POST /api/predict/eta — response body.
 * src/nexafreight/api/schemas/ml.py :: EtaPredictionResponse
 *
 * P10 = optimistic, P50 = median, P85 = conservative (all in days from now).
 * confidence_interval_width = P85 − P10.
 */
export interface EtaPrediction extends MLResponseBase {
  p10_eta_days: number              // Optimistic ETA (days)
  p50_eta_days: number              // Median ETA (days)
  p85_eta_days: number              // Conservative ETA (days)
  confidence_interval_width: number // P85 − P10 spread (days, ≥ 0)
}

/**
 * One time-series point in a demand forecast.
 * src/nexafreight/api/schemas/ml.py :: DemandForecastSeriesPoint
 */
export interface DemandForecastSeriesPoint {
  ds: string                // ISO date string (e.g. "2024-07-15")
  yhat: number              // Point forecast
  yhat_lower: number | null // Lower bound (may be null)
  yhat_upper: number | null // Upper bound (may be null)
  is_forecast: boolean      // true = projected, false = historical
}

/**
 * GET /api/demand/forecast — successful response.
 * src/nexafreight/api/schemas/ml.py :: DemandForecastResponse
 *
 * Query params: ?category=<str>&region=<str>&horizon_days=30|60|90
 */
export interface DemandForecastResponse extends MLResponseBase {
  category: string
  region: string
  series: DemandForecastSeriesPoint[]
  horizon_snapshot: string  // e.g. "90 days"
}

/**
 * GET /api/demand/forecast — 404 when (category × region) lane is unknown.
 * src/nexafreight/api/routes/predictions.py :: demand_forecast (404 branch)
 */
export interface ForecastUnavailable {
  detail: {
    error_code: 'UNKNOWN_LANE'
    message: string
    provenance: 'SYSTEM'
  }
}

/**
 * Standard error envelope for ML endpoints (503 service unavailable).
 * src/nexafreight/api/schemas/ml.py :: MLErrorResponse
 */
export interface MLErrorResponse {
  error_code: string
  message: string
  provenance: string
}

// ─── Operational APIs (Definitive Plan — Phase 10-12) ────────────────────────
// Backend schemas: src/nexafreight/schemas/ops.py
// Endpoints: /api/alerts /api/disruptions /api/decisions /api/analytics /api/copilot

/** src/nexafreight/enums.py :: AlertSeverity */
export type AlertSeverity = 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW'

/** src/nexafreight/enums.py :: AlertStatus */
export type AlertStatus = 'OPEN' | 'ACKNOWLEDGED' | 'RESOLVED'

/** src/nexafreight/enums.py :: DisruptionType */
export type DisruptionType =
  | 'VESSEL_DELAY'
  | 'PORT_CONGESTION'
  | 'WEATHER'
  | 'MANUAL'

/** src/nexafreight/enums.py :: DisruptionStatus */
export type DisruptionStatus = 'ACTIVE' | 'RESOLVED'

/** src/nexafreight/enums.py :: DecisionAction */
export type DecisionAction = 'ACCEPT_DELAY' | 'REROUTE' | 'SPLIT_SHIPMENT'

/**
 * One row of GET /api/disruptions.
 * src/nexafreight/schemas/ops.py :: DisruptionOut
 */
export interface Disruption {
  id: string
  shipment_id: string
  leg_id?: number | null
  disruption_type: DisruptionType
  status: DisruptionStatus
  description?: string | null
  detected_at?: string | null            // ISO-8601
  resolved_at?: string | null            // ISO-8601
}

/** src/nexafreight/schemas/ops.py :: DisruptionsResponse */
export interface DisruptionsResponse {
  disruptions: Disruption[]
}

/** src/nexafreight/schemas/ops.py :: DisruptionCreate */
export interface DisruptionCreate {
  shipment_id: string
  disruption_type: DisruptionType
  delay_hours?: number | null
  description?: string | null
}

/**
 * One row of GET /api/alerts.
 * src/nexafreight/schemas/ops.py :: AlertOut
 */
export interface Alert {
  id: string
  shipment_id: string
  disruption_id?: string | null
  disruption_type?: DisruptionType | null
  severity: AlertSeverity
  status: AlertStatus
  financial_exposure: number             // USD
  created_at?: string | null             // ISO-8601
  acknowledged_by?: string | null
  provenance: Provenance | string        // always present (contract rule)
  source?: string | null
}

/** src/nexafreight/schemas/ops.py :: AlertsResponse */
export interface AlertsResponse {
  alerts: Alert[]
}

/** src/nexafreight/schemas/ops.py :: SlaBreachOut */
export interface SlaBreach {
  order_id?: number | null
  order_number?: string | null
  revenue_usd: number
  days_late: number
  penalty_usd: number
  sla_deadline?: string | null
}

/**
 * GET /api/alerts/{id} — detail with embedded disruption.
 * src/nexafreight/schemas/ops.py :: AlertDetail
 */
export interface AlertDetail extends Alert {
  disruption?: Disruption | null
  sla_breach_details?: SlaBreach[] | null
  description?: string | null
  detected_at?: string | null
}

/** src/nexafreight/schemas/ops.py :: AcknowledgeRequest */
export interface AcknowledgeRequest {
  user_id: number                        // operator id to attest (1 = demo operator)
}

/**
 * One scored reroute option.
 * src/nexafreight/schemas/ops.py :: RerouteOptionOut
 */
export interface RerouteOption {
  option_key: string                     // ACCEPT_DELAY | VIA_PIRAEUS | DIVERT_GENERIC | MODAL_SHIFT_AIR
  action: DecisionAction
  display_name: string
  description: string
  revised_eta?: string | null            // ISO-8601
  cost_delta_usd: number                 // freight premium (0 when accepting)
  sla_penalty_usd: number                // SLA penalties avoided/charged at revised ETA
  demurrage_usd: number                  // projected demurrage exposure
  carbon_cost_usd: number                // $0.08/kg × ΔCO2
  co2_delta_kg: number                   // CO2 change vs current route
  sla_breaches: number                   // breaching orders at revised ETA
  total_impact_usd: number               // composite cost
  recommended: boolean                   // exactly one option is recommended
  assumptions: string[]                  // factor table (transparency)
}

/** src/nexafreight/schemas/ops.py :: OptionsOut */
export interface RerouteOptionsResponse {
  options: RerouteOption[]
}

/**
 * POST /api/alerts/{id}/approve — 201 response body.
 * Backed by schemas in routes/alerts.py (inline dict).
 */
export interface ApproveResponse {
  decision_id: string
  action: DecisionAction
  chosen_option_key: string
  provenance: Provenance | string
}

/** src/nexafreight/schemas/ops.py :: DecisionOut */
export interface Decision {
  id: string
  alert_id?: string | null
  shipment_id?: string | null
  action: DecisionAction
  chosen_option_key: string
  financial_impact: number               // USD
  route_version_before?: number | null
  route_version_after?: number | null
  approved_by?: string | null
  approved_at?: string | null            // ISO-8601
  provenance: Provenance | string
}

/** src/nexafreight/schemas/ops.py :: DecisionsResponse */
export interface DecisionsResponse {
  decisions: Decision[]
}

/** src/nexafreight/schemas/ops.py :: ShipmentSummaryOut */
export interface ShipmentSummary {
  id: string
  status: ShipmentStatus
  mode: TransportMode
  origin?: string | null
  destination?: string | null
}

/** src/nexafreight/schemas/ops.py :: AnalyticsSummaryResponse */
export interface AnalyticsSummaryResponse {
  total_shipments: number
  in_transit: number
  delivered: number
  delayed: number
  sla_breach_count: number
  open_alerts: number
  summary_by_status: Record<string, number>
  shipments: ShipmentSummary[]
  provenance: Provenance | string
}

/** src/nexafreight/schemas/ops.py :: WindowSliceOut */
export interface WindowSlice {
  period: 'day' | 'week' | 'month'
  shipments: number
  total_revenue: number
  total_shipping_cost: number
  decided_margin: number
  undecided_revenue: number
  undecided_pending_sla_est: number
  undecided_pending_demurrage_est: number
  undecided_total_pending_est: number
}

/** src/nexafreight/schemas/ops.py :: AnalyticsFinancialRow */
export interface AnalyticsFinancialRow {
  shipment_id: string
  mode: TransportMode
  status: ShipmentStatus
  revenue_usd: number
  shipping_cost_usd: number
  sla_penalty_usd: number
  demurrage_usd: number
  freight_cost_usd: number
  carbon_cost_usd: number
  total_costs_usd: number
  margin_usd: number
  margin_pct: number | null
}

/** src/nexafreight/schemas/ops.py :: AnalyticsFinancialResponse */
export interface AnalyticsFinancialResponse {
  day: WindowSlice
  week: WindowSlice
  month: WindowSlice
  rows: AnalyticsFinancialRow[]
  provenance: Provenance | string
}

/** src/nexafreight/schemas/ops.py :: AnalyticsSlaRow */
export interface SlaRow {
  shipment_id: string
  sla_status: OrderSlaStatus
  days_to_deadline: number | null
  disrupted: boolean
  disruption_description?: string | null
  delay_days: number | null
}

/** src/nexafreight/schemas/ops.py :: AnalyticsSlaResponse */
export interface AnalyticsSlaResponse {
  rows: SlaRow[]
  provenance: Provenance | string
}

/** src/nexafreight/schemas/ops.py :: AnalyticsEsgRow */
export interface EsgRow {
  shipment_id: string
  mode: TransportMode
  kg_co2: number
  kg_co2e_per_container: number
  vs_air_co2_saving_pct: number | null
  vs_air_freight_delta_pct: number | null
}

/** src/nexafreight/schemas/ops.py :: AnalyticsEsgResponse */
export interface AnalyticsEsgResponse {
  rows: EsgRow[]
  route_breakdown: Record<string, number>
  provenance: Provenance | string
}

/**
 * GET /api/shipments/{id}/predict → 200.
 * src/nexafreight/schemas/ops.py :: ShipmentPredictResponse
 */
export interface ShipmentPredictResponse {
  shipment_id: string
  delay_p50_hours: number                // clamped at ≥ 0
  sla_risk_level: 'ON_TIME' | 'LOW' | 'MEDIUM' | 'HIGH' | 'BREACH' | string
  model_version?: string | null
  provenance: 'DERIVED' | 'FALLBACK' | Provenance | string
}

/** src/nexafreight/schemas/ops.py :: FinancialOrderOut */
export interface FinancialOrder {
  order_number: string
  revenue: number
  shipping_cost: number
  sla_status: OrderSlaStatus
}

/** src/nexafreight/schemas/ops.py :: PnlSnapshotOut */
export interface PnlSnapshot {
  revenue_usd: number
  shipping_cost_usd: number
  sla_penalty_usd: number
  demurrage_usd: number
  freight_cost_usd: number
  carbon_cost_usd: number
  total_costs_usd: number
  margin_usd: number
  margin_pct: number | null
  warnings: string[]
}

/**
 * GET /api/shipments/{id}/financials → 200 (403 for VIEWER role).
 * src/nexafreight/schemas/ops.py :: ShipmentFinancialsResponse
 */
export interface ShipmentFinancialsResponse {
  shipment_id: string
  container_count: number
  container_weight_t: number             // 14 t/container per the finance model
  orders: FinancialOrder[]
  pnl: PnlSnapshot
  provenance: Provenance | string
}

/**
 * POST /api/copilot/ask → 200.
 * src/nexafreight/schemas/ops.py :: CopilotAskResponse
 */
export interface CopilotAskResponse {
  answer: string
  source: 'llm' | 'rules' | 'rules_fallback'
  provenance: Provenance | string
}
