"""Add parameter tables

Revision ID: 8420d96dacf5
Revises: 002_composite_index
Create Date: 2026-09-21 13:59:25.670873+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8420d96dacf5'
down_revision: str | None = '002_composite_index'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parameter_empirical',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('derivation_method', sa.Text(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_parameter_empirical'))
    )
    op.create_table('parameter_policy',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_parameter_policy'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parameter_policy')
    op.drop_table('parameter_empirical')
    # ### end Alembic commands ###
