"""add external_events

Revision ID: b2c3d4e5f6a7
Revises: c5e6f7a8b9d0
Create Date: 2026-09-26 22:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2c3d4e5f6a7'
down_revision: Union[str, None] = 'c5e6f7a8b9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('provenance', sa.String(length=20), server_default='REAL', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_events')),
    sa.UniqueConstraint('source', 'external_id', name='uq_external_events_source_external_id')
    )
    op.create_index(op.f('ix_external_events_event_time'), 'external_events', ['event_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_external_events_event_time'), table_name='external_events')
    op.drop_table('external_events')
    # ### end Alembic commands ###
